language: node_js
node_js: node
sudo: required
deploy:
  provider: heroku
  api_key:
    secure: t81MPYRMt7vfqUHWaYxkU0boujtpUsT0PIfp2g0KGRNBMvVH5baHW2re7Wfyl+UOOcaFGZ6vfLJiwpf/dRxS17xBwhF5hw7UGrwCZEKl/1x6M9kRUw+Zq7qIDKHIlecJ0cocd0FZYTceGyt9q8JeEDxF18EkpMKF1LrrD4ipmLo7ny2Xwm87flCk28B1oMTOdDPYPSBmXnrVeDjtD8T+pwLwJVseehXae06iJpk2Pt7DLBavMwR3Gy7lxpFjpOi3qg7zbb+caxz7yceGKoNnM04tMULWsdxe9S7rkUJdGJIHtn2RCaUrmvQtfMxSr4b4xcv1d+RwGCXa/lrWIUoNY99EGPfGNMI1FSgZgCb8r9q2gT25tgAY/ZaSCN+y2Iz3Eszfb8UIkbFxM7yQ4/QCCw+QaOuXNgh/X7D+YiS/sA/SCLqYDhHYlMlfczVDR8N0dkRXVQzbSiLgN/hASstKs5xHHi/9YBjga5jbKMarbasggQESOyj4CXSY4wfqF8LF42rcVpAhdfjtsw6z8PBwkvRk7h+I3DtXxIjvve+jChjXpI4RE0nUQadDWjTaJg2oQDtHfFb61UzO8Z6sPOlrWkVCFife7pnkwsCvUsoKt12yccRmOsCk/bxtRJjJQ+6JLxZ7HQ6oyBg4HmUKfViMapUHS1bNvIYy7QDk0ahLxPc=
  app: pacific-meadow-78178
  on:
    repo: TheSaintMichael/blog-api-v1
before_script: chmod 0777 ./node_modules/.bin/mocha